from PyQt5 import QtGui

logoDefault = [ "128 128 107 2 ",
"   c #000000",
".  c #0B0B06",
"X  c #040609",
"o  c #06090C",
"O  c #0B0B0B",
"+  c #16160D",
"@  c #090D12",
"#  c #0B1017",
"$  c #0E141C",
"%  c #131313",
"&  c #11171F",
"*  c #12181F",
"=  c #1B1B1B",
"-  c #252514",
";  c #2C2C18",
":  c #37371E",
">  c #101720",
",  c #131A24",
"<  c #151E2A",
"1  c #16212E",
"2  c #182432",
"3  c #1E2C3E",
"4  c #242424",
"5  c #2B2B2B",
"6  c #3F3F22",
"7  c #333333",
"8  c #3B3B3B",
"9  c #424223",
"0  c #4C4C29",
"q  c #53532D",
"w  c #5A5A31",
"e  c #606034",
"r  c #71713D",
"t  c #202E41",
"y  c #223245",
"u  c #25354A",
"i  c #27384E",
"p  c #293C54",
"a  c #2B3F58",
"s  c #2D415C",
"d  c #304662",
"f  c #334966",
"g  c #354C6B",
"h  c #375070",
"j  c #3A5375",
"k  c #3C567A",
"l  c #3E597D",
"z  c #444444",
"x  c #4A4A4A",
"c  c #555555",
"v  c #5B5B5B",
"b  c #7B7B42",
"n  c #626262",
"m  c #6C6C6C",
"M  c #737373",
"N  c #7C7C7C",
"B  c #8A8A4A",
"V  c #91914E",
"C  c #969651",
"Z  c #989852",
"A  c #A4A459",
"S  c #A9A95B",
"D  c #B6B662",
"F  c #BBBB65",
"G  c #C6C66B",
"H  c #D2D271",
"J  c #DADA76",
"K  c #E3E37A",
"L  c #EAEA7E",
"P  c #3F5B80",
"I  c #405D82",
"U  c #436187",
"Y  c #45648C",
"T  c #476790",
"R  c #476891",
"E  c #4A6B96",
"W  c #4C6E9A",
"Q  c #4E719E",
"!  c #4F73A1",
"~  c #5276A6",
"^  c #557BAD",
"/  c #577EB0",
"(  c #587FB2",
")  c #5981B4",
"_  c #5C85BB",
"`  c #5E88BF",
"'  c #5F89C0",
"]  c #618DC5",
"[  c #638FC8",
"{  c #6592CC",
"}  c #6795D0",
"|  c #6896D2",
" . c #6998D5",
".. c #6C9DDC",
"X. c #6FA1E1",
"o. c #70A2E3",
"O. c #808080",
"+. c #8B8B8B",
"@. c #939393",
"#. c #9B9B9B",
"$. c #A5A5A5",
"%. c #ABABAB",
"&. c #B4B4B4",
"*. c #BCBCBC",
"=. c #EFEF81",
"-. c #C0C0C0",
";. c None",
";.;.;.                                                                                                                                                                                                                                                    ;.;.;.",
";.;.                                                                                                                                                                                                                                                        ;.;.",
";.;.    y E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E g     ;.;.",
";.;.    ] o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.>     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.{ W g y s Y _ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o...g               3 ] o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o._ ,       - q : .     o T o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .$     e K =.=.=.L V .     ^ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.s     S =.=.=.=.=.=.=.H -   & ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.^     r =.=.=.=.=.=.=.=.=.F     g o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.] j , 1 u  .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.j   + L =.=.=.=.=.=.=.=.=.=.w   < o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .T 3           y o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.t   0 =.=.=.=.=.=.=.=.=.=.=.C   X ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.^ a o       X 7 5     ^ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.#   b =.=.=.=.=.=.=.=.=.=.=.G     ) o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.{ j >         4 x N O.N %   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.$   r =.=.=.=.=.=.=.=.=.=.=.F     _ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o...E 3         % 8 M O.O.O.O.O.8   @ ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.i   6 =.=.=.=.=.=.=.=.=.=.=.B   o o.o.o.o.o.o.o.o.o.o.o.o.o.o.) s O       X 5 v O.O.O.n x c m O.m     ~ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.l   . J =.=.=.=.=.=.=.=.=.=.9   2 o.o.o.o.o.o.o.o.o.o.o.{ l ,         = x N O.O.M z %       % M O.%   a o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.] X   0 =.=.=.=.=.=.=.=.=.Z     I o.o.o.o.o.o.o.o...W y         O 8 M O.O.N c 4   X     O     5 O.z   o ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.k     r L =.=.=.=.=.=.S .   3 o.o.o.o.o.o.o._ d @       X 5 v O.O.O.n 7 O       O x @.-.v     x m     W o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ; A J =.K D w     o ] o.o.o.o.| P <         = x N N O.M z %         7 N &.-.-.-.x     X N =   p o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .p         + X       , _ o.o...Q u         O 8 m O.O.N c 4 X       = n $.-.-.-.-.-.-.x       c z   o ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.W >               R o.] f @         5 v N O.O.n 8 O       O z +.-.-.-.-.-.-.-.-.-.+.      4 m     E o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.| ~ k j         y X       = x N N O.M z =         5 N &.-.-.-.-.-.-.-.-.-.-.-.&.O     X N =   i o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.&           X 8 n O.O.N v 5         % v $.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.x       c x   X  .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.h           c O.O.O.x O         z +.*.-.*.&.N n M -.-.-.-.-.-.-.-.-.-.-.@.      7 M     R o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.'           c O.O.z       4 M &.-.-.-.-.*.4       x -.-.-.-.-.-.-.-.-.-.*.4     8 O.4   t o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<         4 O.O.O   5 #.-.-.*.-.-.-.*.n     O     M -.-.-.-.-.-.-.-.-.-.*.4   = O.x   X  .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.k           N O.O   M -.-.-.-.-.-.-.-.7   = v =   % &.-.-.-.-.&.M c m -.-.O.    M M     T o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.[     3     4 O.%   z -.-.-.-.-.-.-.-.c   O v x     v -.-.*.O.%       z *.*.O   z N 4   3 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2   u #     v z   O &.-.-.-.-.-.-.-.@.    7 v 4   X %.%.8       O     O.-.z   = O.x     | o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.I     k     O n     O.-.-.-.-.-.-.-.*.8   O c c X   4 O     % x v O   n -.O.    m M X   Y o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.|     P X     = =   8 -.-.-.-.-.-.-.-.$.X   5 8 %       X 7 v v z     v -.*.O   z N 4   3 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.t   3 t       4   O &.-.-.-.-.-.-.-.-.c               7 v c 4     % &.-.-.x   % O.c     { o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.T     I             N -.-.-.-.-.-.-.*.&.O     X 4 O     7 X     = #.-.-.-.+.    m N     I o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .X   k X   O       8 *.-.-.-.-.-.-.%.z       8 4 8         X n *.-.-.-.-.*.    O m 4   2 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.u   2 y   =       X &.-.-.-.-.-.M O         8 4 8       7 $.-.-.-.-.-.-.@.      z c     ] o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.W     I     x       N -.-.-.$.5       7 X   X 5 O     X %.-.-.-.-.-.-.-.%.      O N X   l o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o...o   h X   x 5     5 -.-.*.4     = c v 7               x -.-.-.-.-.-.-.-.5       m 5   1 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.p   , 2   = N O     #.-.m     8 v v 8 X       % 8 5     #.-.-.-.-.-.-.-.M       8 c     ] o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.~           M v     = *.m   X v x =     X 4     c v O   5 -.-.-.-.-.-.-.%.      O N X   j o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.T           z O.%     v @.    O X     5 $.&.O   = v 8     O.-.-.-.-.-.-.-.5     X N 5   < o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.[ t       @ i   = O.z     v -.x       O N *.-.-.m     x v %   z -.-.-.-.-.-.-.+.O   O O.v     _ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.I o     1     k     m 5     m -.-.M c m %.-.-.-.-.&.=   % v 4   4 -.-.-.-.-.-.-.-.N     N N O   j o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.    | o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.` 2     o Y o.$   s o   8       7 -.-.-.-.-.-.-.-.-.-.-.O.    O     x -.-.-.-.-.*.-.$.7     O.N 7   > o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.j X     u { o.o.g   # p   O   O     %.-.-.-.-.-.-.-.-.-.-.-.c       = &.-.-.-.-.&.N 7       8 O.O.v     ] o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.g   # W o.o.o.o._     j       z X   m -.-.-.-.-.-.-.-.-.-.-.-.N v M &.-.-.*.@.x O       X 8 O.O.O.n     ] o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o...g  .o.o.o.o.o.o.,   p       N 5   5 -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.%.n =         4 c N O.N M 8 O     } o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.j   o     O O.c     %.-.-.-.-.-.-.-.-.-.-.-.-.&.N 7         % z M N O.N c 4       X Q o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.]           m N X   m -.-.-.-.-.-.-.-.-.-.#.x O       X 7 n O.O.O.n 7 O       @ d _ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     o   8 O.5   5 *.-.-.-.-.-.-.%.n 4         4 x N N O.M z %         t W ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.p     p   % O.v     $.-.-.-.*.N 7         % 8 M O.O.N c 4         > k { o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.[       g     n N O   v -.#.x O X     X 5 v N O.O.n 7 O       o s ( o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.s       t #   8 O.7     O         = x N N O.N z =         3 R ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.[     <     s   O O.N %       O 8 m O.N N c 5         $ j [ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.s   @ [ X   g     n O.M x z v O.O.O.m 8 O       o p ^ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.] X   j o.y   3 #   8 O.O.O.N O.N x %         2 T ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.s   @  .o.E     s   O O.O.N v 5         # j ] o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.]     k o.o. .X   d     5 8 O       X p ~ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.s   @  .o.o.o.p   1 s           2 Y  .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.[     j o.o.o.o.!     _ u > > g ` o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.( , @  .o.o.o.o.o.@   j o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o...' o.o.o.o.o.o.s   > o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.~     _ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.#   p o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.g $ y o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.) $   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.P       s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .y         s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o._ $     t 2   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.l X     l o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .y     # ^ o.o.t   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o._ $     t | o.o.o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.    | o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.l       l o.o.o.o.o.t   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .y     # ^ o.o.o.o.o.o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.) $     t | o.o.o.o.o.o.o.t   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.P X     k o.o.o.o.o.o.o.o.o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.     .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .y     # ( o.o.o.o.o.o.o.o.o.o.t   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    p ] o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.( $     t  .o.o.o.o.o.o.o.o.o.o.o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.        i _ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.I X     k o.o.o.o.o.o.o.o.o.o.o.o.o.t   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    X       y ( o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .y     # ^ o.o.o.o.o.o.o.o.o.o.o.o.o.o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.    z 7 O       3 ^ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.p     t | o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c 7 O       2 Q o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.l   X o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.t   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.    x c c c c 7 %       < E X.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o._     _ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    z c c c c c c 8 %       > T o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o...X   U o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.t   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c v 8 %       # I ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.2   p o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.    x c c c c c c c c c c z =       @ k  .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.g   > o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    z c c c c c c c c c c c c z =       @ g | o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.W     } o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.t   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c z 4       X f { o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.|     Q o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c x 4         s [ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.>   g o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.t   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.<     ;.",
";.;.    z c c c c c c c c c c c c c c c c c c c 4 X       p ` o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.p   2 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.3   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c x 5 O       u _ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.U   X X.o.o.o.o.o.o.o.o.o.o.o.o.o.o.t   3 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c x 5 O       3 ^ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o._     ( o.o.o.o.o.o.o.o.o.o.o.o.o.o.P     ^ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c 7 O       2 ~ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o   l o.o.o.o.o.o.o.o.o.o.o.o.o.o.X.>   2 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c 7 O       1 W o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.t   u o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.E     Q o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 7 %       , T o.o.o.o.o.o.o.o.o.o.o.o.o.j   # o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.1   , X.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    z c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 8 %       $ U ..o.o.o.o.o.o.o.o.o.o.^     [ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.~     Y o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c z %       # l ..o.o.o.o.o.o.o.o. .    R o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.3   # ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c z =       O j  .o.o.o.o.o.o.o.<   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o._     l o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    z c c c c c c c c c c c c c c c c v c c c c c c c c c c c c c v c c c c c c z =       o g | o.o.o.o.o.s   < o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.X.i   o  .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c x 4 X     X d { o.o.o.E      .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.]     g o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c x 4         p ] o.]     ^ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.d   X [ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    z c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c x 5 X       i _ #   j o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.} X   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.>     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c x 5 X       #   3 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.j     ` o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 5 O         ^ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .@   y o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 7 O       2 ! o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.I     ( o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c v c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 8 O       < E X.o.o.o.o.o.o.o.o.o.o.o.o.o.X.&   2 o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 8 %       > Y o.o.o.o.o.o.o.o.o.o.o.o.o.R     Q o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    z c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 8 %       # I ..o.o.o.o.o.o.o.o.o.o.o.1   < o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c z =       @ k  .o.o.o.o.o.o.o.o.o.~     T o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c z =       @ j | o.o.o.o.o.o.o.o.3   # ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.>     ;.",
";.;.    z c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c x =       X f { o.o.o.o.o.o._     l o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c x 4       X s [ o.o.o.o.o.i   #  .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.>     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c x 4 X       p _ o.o.o.]     g o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 4 X       u _ o.o.d   X { o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c v c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 5 O       t ^ { X   s o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.*     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 7 O       3 p   X ' o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.>     ;.",
";.;.    z c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 7 O           u o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.,     ;.",
";.;.    z c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 8 O         l X.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.&     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 8 %       $ U ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.*     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c v c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 8 =       # l  .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.>     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c z =       @ k  .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.*     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c x =       o g | o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.*     ;.",
";.;.    z c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c x 4       X d { o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.*     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c x 4         s ] o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.&     ;.",
";.;.    x c c c c c c c c c c c c c c c c c c c c c c c c c c v c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c x 5 X       i _ o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.&     ;.",
";.;.    8 c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c 5 X       y ) o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o     ;.",
";.;.    X = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = O X       # f g g g g g g g g g g g g g g g y     ;.;.",
";.;.                                                                                                                                                                                                                                                        ;.;.",
";.;.;.                                                                                                                                                                                                                                                    ;.;.;."  ]

logo = None

def getPixmap():
    global logo

    if not logo:
        logo = QtGui.QPixmap(logoDefault)
    return logo

def getLogo():
    return QtGui.QIcon(getPixmap())

